tests/importStudents/README.md
tests/importStudents/testBannerRoster.csv
tests/importStudents/testBannerRoster.md

The commits in this PR add a sample Banner CSV roster to facilitate testing of the eventual resolution to Issue #51 (add student users in bulk). A README file is also added.
The sample roster is added to the `tests` folder so it can become part of unit testing the code to add student users in bulk.

Add test Banner roster

---

src/addRoleBaseMgmt.sql
src/addUserMgmt.sql
tests/testRoleBaseMgmt.sql
tests/testUserMgmt.sql

Commit b4f416c adds the initial version of `addUserMgmt.sql`. Commit 714774d adds `testUserMgmt.sql` containing some initial, rudimentary, nominal unit tests. 
**File `addUserMgmt.sql` needs a through review** because it has trigger definitions that can make or break the system. 
Commit 73e0f5f opportunistically adds a [test case previously identified](https://github.com/DASSL/ClassDB/pull/143#issuecomment-356129488).

Initial version of addUserMgmt.sql

---

src/initializeDB.sql

This PR changes the privileges on the `classdb` schema so that instructor and DB managers only have the `USAGE` privilege. Previously, they were incorrectly given `ALL PRIVILEGES`.
So far in my preliminary testing, this does not seem to impact the functionality of any part of the system. However, I still need to test a bit more since this is a relatively significant change.
Fixes #148

Grant only Usage on classdb schema to instructors and DB managers

---

tests/privileges/0_setup.sql
tests/privileges/1_instructorPass.sql
tests/privileges/2_studentPass.sql
tests/privileges/3_dbmanagerPass.sql
tests/privileges/4_instructorPass2.sql
tests/privileges/5_instructorFail.sql
tests/privileges/6_studentFail.sql
tests/privileges/7_dbmanagerFail.sql
tests/privileges/8_cleanup.sql
tests/privileges/runAllPrivilegeTests.psql
tests/privileges/testPrivilegesREADME.txt

Previously, none of the privilege tests functioned as they should since they were still using V1.0's API and objects. They have now been updated to work with M2 (V2.0), and have had new objects added to which privileges needed to be tested.
No issues have been identified with the current state of privileges. Also, no major issues were identified with the functionality of the system.
Additionally, running privilege tests no longer require the user to manually reconnect to the database and type in a script name. This is now taken care of by a `psql` script. The readme has also been updated to reflect this.
Many code-consistency fixes were also make to the tests themselves.
No modifications to the system were done in this PR.

Update privilege tests

---

src/db/reco/addFrequentViewsReco.sql

Commit 9765503 fixes #181 and #182
- View `StudentTable` now returns both user name and schema name, and it works on all tables and views students own independent of schema name and ownership.
- It now uses `pg_catalog` instead of `INFORMATION_SCHEMA`, because the latter does not provide all the information needed
- View `StudentTableCount` now returns user name and just reuses view `StudentTable`
- Columns in both views now have appropriate names
- General: adjusted line spaces and put ownership grants first in permission blocks.

Fix StudentTable and StudentTableCount

---

tests/privileges/runAllPrivilegeTests.psql

The `\i` flag has been replaced with `\ir` and a psql command has been added that sets `ON_ERROR_STOP` to off before running the script.
For more information, see issue #187

Fix privilege tests: Use ir flag and set on_error_stop to off in runAllPrivilegeTests.psql

---

src/db/reco/addFrequentViewsReco.sql

This PR adds the new user views discussed for #184. A summary of the changes:
- The old `StudentActivityAll` and `StudentActivityAnon` views have been removed
- All `ClassDB.getUserXYZActivity()` functions now supply `NULL` for the default parameter
- When `NULL` is passed, the function returns activity records for all users
- New functions:
- `ClassDB.getStudentActivitySummary()`: Like `getUserActivitySummary()`, but restricted to students
- `ClassDB.getStudentActivitySummaryAnon()`: Anonymized version of `getStudentActivitySummary()`
- `ClassDB.getStudentActivity()`: Like `getUserActivity()` but restricted to students
- `ClassDB.getStudentActivityAnon()`: Anonymized version of `getStudentActivity`
- New views:
- `ClassDB.StudentActivitySummary`: View wrapping …

Add new user views

---

src/db/core/addRoleBaseMgmtCore.sql

Fixes #192
Removed the "helpful" notice that used to be raised if role had more ClassDB roles after revoking a role.

Remove notice in revokeClassDBRole

---

src/db/core/addClassDBRolesMgmtCore.sql
src/db/core/addHelpersCore.sql
src/db/core/addRoleBaseMgmtCore.sql
tests/testClassDBRolesMgmt.sql
tests/testRoleBaseMgmt.sql

Fixes #191
Commit a6802a7 makes the following changes:
- Change default value of `objectsDisposition` in function `dropRole` to `'assign'` from `'assign_i'` and remove choices of `'assign_i'` and `'assign_m'` for that parameter.
- Prevent a ClassDB group role from becoming the new owner.
- Make `SESSION_USER` the default new owner if no new owner is specified.
The changes turned out to be a bit more involved than I'd thought it would be. Everything appears to work in the limited testing I have done so far, but I need to review the code again tomorrow with fresh eyes and run broader tests. In the meanwhile, let me know if any of you find any issue.
BTW, I believe I need to revise `testRoleBaseMgmt.sql` because one of the test cases there no longer applies.

Change default value of objectsDisposition in dropRole

---

src/db/core/addClassDBRolesViewsCore.sql
src/db/reco/addFrequentViewsReco.sql
tests/testAddConnectionActivityLogging.psql
tests/testAddConnectionActivityLoggingCleanup.sql
tests/testAddDDLActivityLogging.sql

This is a collection of small fixes/improvements to the logging tests scripts and user views. I intended for this to be two separate PRs, but I accidentally merged all the changes into one commit.
- The logging tests no longer fail due to the new drop dispositions. The new [removing users](https://github.com/DASSL/ClassDB/wiki/Removing-Users) page helped a lot with making this change easy (@afig)
- The `ClassDB.StudentActivitySummaryAnon` view now calls the correct underlying function
- `ClassDB.getUserAcitivity()` orders activity records by username, so all views/functions that return individual activity records are now ordered by username.
With these changes, all tests pass a new ClassDB instance setup using the new quick-start guide 🎉

Make logging tests use new drop dispositions and improve user views

---

src/db/core/addClassDBRolesMgmtCore.sql

Simplifies code in ```isStudent```, ```isInstructor```, and ```isDBManager``` functions within ```addClassDBRolesMgmtCore.sql``` as pointed out in issue #208. All unit test continue to pass after this (small) change.

Remove unnecessary code from isXYZ functions

---

src/db/core/addHelpersCore.sql
src/db/core/initializeDBCore.sql
src/server/core/initalizeServerCore.sql
src/server/removeAllFromServer.sql

The commits in this PR add a new server role `ClassDB_Team` in preparation for team support. User and ClassDB role management need the server role to support teams. (Those changes are and should be subject of another PR).

Define server team role

---

src/db/core/addClassDBRolesMgmtCore.sql
tests/testClassDBRolesMgmt.sql

This pull request is for issue #201 and the CreateXYZ functions were changed to incorporate those changes suggested by @smurthys in that issue thread. 
This is not ready to be approved but I wanted to get opinions on how to handle the changed test script for the new CreateXYZ functions. All I did was change the test script `testClassDBRolesMgmt.sql` so that the tests on the passwords were testing on the initial password. However, this should raise 3 warnings for each test for a total of 9 warnings. It may be useful to see that a warning pops up to see that the new addition is working correctly but I am not sure it is worth doing 9 times. 
Maybe we should change it so each test function incorrectly supplies a password once. Also suppressing the warning might be a good idea since it will be …

Make CreateXYZ functions Safe

---

src/db/core/addClassDBRolesMgmtCore.sql
src/db/core/addRoleBaseMgmtCore.sql
tests/testClassDBRolesMgmt.sql

This PR focuses on adding functions to create, revoke, and drop teams in ClassDB. In particular, it leaves out functionality that manages team membership, which will be added in a separate PR due to the large number of changes.
Unit tests for all 4 functions have been created, and all pass on my instance except for `testCreateTeam()`, which fails with Code 4 due to a pending decision related to optional `fullName`s (see Issue #218). Currently, if a `fullName` is not provided, it is set to `teamName` (final behavior will depend on the decision made in #218, as such, **do not approve this PR** until then).
As @smurthys discussed in PR #211, the tests in `testClassDBRolesMgmt.sql` need several improvements in relation to avoiding unnecessary operations and improving consistency. The new …

Add team management

---

src/db/core/addHelpersCore.sql
tests/testHelpers.sql

This PR adds the following functions:
- `getServerSetting` get any server setting by name
- `getServerVersion` to get server's version number
- `compareServerVersion` to compare a version number with current server's, or compare any two version numbers
I am still working on a test script for these changes.
Closes #231

Add functions to get and compare server versions

---

src/db/core/addClassDBRolesViewsCore.sql

Adds the team views: ClassDB.Team and ClassDB.TeamMember. Fixes #236 
The view TeamMember displays all roles that are added to a team and their respective team(s).
The view Team displays all teams with their attributes and an aggregate `MemberCount`.
In order to test this properly the `ClassDB.addToTeam` function from branch `add-teams-membership` will need to be added.
I added it manually to my local ClassDB and everything seems to working properly.

Add Team Views

---

src/db/core/addClassDBRolesMgmtCore.sql
src/db/core/addHelpersCore.sql
tests/testClassDBRolesMgmt.sql
tests/testHelpers.sql

This PR implements changes that allow students to become members of a team. Becoming a member of a team allows students to create and access objects in the team's shared schema.
In regards to team membership, three functions have been created: `addToTeam()`, `removeFromTeam()`, and `removeAllFromTeam()`. As discussed in PR #221 , `removeFromTeam()` also reassigns ownership of objects in the teams schema to the team whenever a student is removed. To do so, two other functions have been added: `reassignObjectOwnership()` and `reassignOwnedInSchema()`.
Tests have been created to verify the nominal functionality of the new functions. These tests could be expanded further, particularly for exceptional cases, but I believe the current tests will suffice for M3. 
A couple of semi-related changes …

Add teams membership

---

src/db/core/addUserMgmtCore.sql

This PR adds a comment to the top of `addUserMgmtCore.sql` discussing the inclusion of objects related to reco components in a core script as discussed in #217.
Closes #217

Added comment about reco components in addUserMgmtCore.sql

---

src/db/core/addClassDBRolesMgmtCore.sql
src/db/core/addClassDBRolesViewsCore.sql
src/db/core/addHelpersCore.sql
src/db/core/addRoleBaseMgmtCore.sql
src/db/opt/addCatalogMgmtOpt.sql
src/db/reco/addConnectionMgmtReco.sql
src/db/reco/addDDLActivityLoggingReco.sql
src/db/reco/addFrequentViewsReco.sql
src/db/removeAllFromDB.sql
src/server/reco/disableConnectionLoggingReco.psql
src/server/reco/enableConnectionLoggingReco.psql
src/server/removeAllFromServer.sql
tests/testRoleBaseMgmt.sql

Changed comments that use old filenames to the updated filenames. Fixes #212 
Also, removed the now unnecessary comment in `addClassDBRolesMgmtCore.sql` : 
`--This script should be run after addConnectionMgmt.sql`

update file names with correct names

---

src/db/reco/addFrequentViewsReco.sql
src/db/removeAllFromDB.sql

Adds manually removal of `ClassDB.getSessionID()` in the installer, because it is a superuser function. Also adds the message suppression to `addFrequentViewsReco.sql`, which I forgot to push before.

Added getSessionID() to uninstaller

---

tests/testConnectionActivityLogging.psql

This fixes the observed errors in `testConnectionActivityLogging.psql` by limiting the second import to `CURRENT_DATE`. There may be a more robust way perform this test, but I would need more time to analyze the issue.
In a nutshell, I believe what was happening is that when there are connections in `ClassDB.ConnectionActivity` that are at least two days old, `importConnectionLog()` will always return more than one row. The issue arises when the first import is performed. If there are no current users with connection activity on the dates imported, then no rows are added to `ClassDB.ConnectionActivity`. Thus, when `importConnectionLog()` is run in the test proper, more than one row is returned, which is an error.
This is definitely a test design issue rather than a ClassDB issue, however.

Fix testConnectionActivityLogging.psql when importing old logs

---

src/db/core/initializeDBCore.sql
tests/privileges/1_instructorPass.sql
tests/privileges/2_studentPass.sql
tests/privileges/3_dbmanagerPass.sql
tests/privileges/6_studentFail.sql

Instructors, DBManagers, and Students can now create schemas. Students still cannot drop schemas.
Privilege tests were updated to test this functionality.
Closes: #251

Allow creation of schemas by ClassDB users

---

src/db/core/addRoleBaseMgmtCore.sql
src/db/core/addUserMgmtCore.sql

This commit fixes #230 by using `CREATE INDEX IF NOT EXISTS` only if the server version is 9.5 or later.

Guard CREATE INDEX IF NOT EXISTS for Postgres 9.4 or earlier

---

src/db/core/addUserMgmtCore.sql
tests/testUserMgmt.sql

The commits in this PR make the following changes:
- Add triggers to prevent row deletion over tables `DDLActivity` and `ConnectionActivity`. The ClassDB role or a superuser can still truncate these tables.
- Update test script for the new triggers. Also fixes a bug in the part that tested existence of triggers: used to test if at least one of the triggers are defined, instead of testing if all expected triggers are defined.
In future we should also consider preventing direct truncation of these table. For that we need to also implement functions to initiate truncation so the tables can be somehow purged. However, this functionality needs to be discussed as part of a larger log-management feature set.
Fixes #176

Reject row deletion over tables DDLActivity and ConnectionActivity

---

src/db/reco/addDDLActivityLoggingReco.sql
tests/testDDLActivityLogging.sql

This PR adds a gaurd for pg_event_trigger_ddl_commands() in `addDDLActivityLoggingReco.sql` by checking server version. If the server version is pre-9.5 the `objId` will be set to N/A. 
N/A is probably not the best name for it and I am open to suggestions. It should contain at least one illegal identifier character so that it can not be confused for a valid object name.  
I had to also update `testDDLActivityLogging.sql` to support these changes. In order to allow users to check server version I had to `GRANT` temporary execution permission to related server version functions. 
fixes #234

Guard uses of pg_event_trigger_ddl_commands() for Postgres 9.4 or earlier

---

src/db/reco/addConnectionMgmtReco.sql
src/server/core/initalizeServerCore.sql

The changes in this PR guard the use of the predefined server role `pg_signal_backend` only in versions 9.6 or later. Fixes #225 
**Note:** Using the server version to address this issue is technically incorrect because the functionality in question is determined by the existence of a specific server role which can be tested in the `pg_roles` table. However, testing for server version is more practical and maintainable, and we should be able to trust no one has removed a server role. (We make many such assumptions about the environment.)

Guard use of pg_signal_backend

---

src/db/core/initializeDBCore.sql
tests/testRoleBaseMgmt.sql

This PR changes two uses of `GRANT` query involving `CURRENT_USER`:
- `initializeDBCore.sql`: Use a guard to execute dynamic SQL for granting
- `testRoleBaseMgmt.sql`: Reuse helper function `ClassDB.grantRole` to keep the script simple and maintainable
Fixes #229

Guard GRANT to CURRENT_USER in pg9.4 or earlier

---

tests/testDisallowSchemaDrop.sql

This PR adds a temporary function that when given a `DROP OWNED BY` query it will dynamically execute the query with an attached `CURRENT_USER`. All uses of `DROP OWNED BY CURRENT_USER` have been replaced with this temporary function with the replaced query as the parameter. This also maintains the purposefully odd case of `DrOP oWNeD BY ` on Ln120.
Fixes #269

Add Guard for DROP OWNED BY

---

src/server/core/addAllServerCore.psql
src/server/core/initializeServerCore.sql

This PR corrects the filename for the server initialization script from `initalizeServerCore.sql` to `initializeServerCore.sql`. Corresponding changes were made elsewhere, including the Scripts page of the documentation.
Fixes #272

Fix server initialization filename

---

src/db/removeAllFromDB.sql

Added a drop function to `removeAllFromDB.sql` which incorporates a drop for `ClassDB.killConnection(INTEGER)` which was previously breaking the script. 
Fixes #225

Fix removeAllFromDB.sql
